/*
Student: John Felt
HW 8 Assignment:
- Write an application with four (4) separate .java files and a manifest .txt file: 
- An interface, such as Returnable, with two methods.
- Two classes that have non-empty implementations of the interface, such as Book.java and Sweater.java
- A class with main that exercises the implemented methods on both kinds of objects, such as InterfaceImplementationDemo.java
- manifest.txt file that tells the command-line jar utility which class has the main method

Note about the logic: I'm also taking a statistics course at UC Berkeley and learning about Standard Deviation.  This program 
intended to show that the Standard Deviation for the sample set of a population should be similar to the SD for the full population for
sample sizes greater than 20.  The equation for the sample SD is identical to the population SD except the denominator is n-1 rather than n.
The program works but the results aren't what I expected. I thought the SDs for the sample size of a population > 20 would be closer but they aren't.

Usage Instructions to run the  program:
java StatsInterfaceDemo

Sample Output:
C:\UCBerkeleyJava>java StatsInterfaceDemo
This program will generate a number of random integers between 0 and 50
to be used to calculate the Standard Deviation for both the full set and a sample set of those integers.
Please enter an integer between 10 and 100 to choose the number of integers to be generated:
10
This loop will print out each random integer stored in myInteger array: 0 value is: 45
This loop will print out each random integer stored in myInteger array: 1 value is: 24
This loop will print out each random integer stored in myInteger array: 2 value is: 37
This loop will print out each random integer stored in myInteger array: 3 value is: 49
This loop will print out each random integer stored in myInteger array: 4 value is: 32
This loop will print out each random integer stored in myInteger array: 5 value is: 42
This loop will print out each random integer stored in myInteger array: 6 value is: 41
This loop will print out each random integer stored in myInteger array: 7 value is: 42
This loop will print out each random integer stored in myInteger array: 8 value is: 22
This loop will print out each random integer stored in myInteger array: 9 value is: 18

This is the average of the 10 random integers between 0 and 50: 35.2
This is the standard deviation for the population of those integers: 10.107423014794623

This is the average of a sample of the random integers: 30.0
This is the standard deviation for a sample of the random integers: 7.71722460186015
(the sample was generated by chosing 6 even numbers from the random set.)

*/
import java.util.*;

public class StatsInterfaceDemo
{
  public static void main(String[] args)
  {		
		
  		//Instantiates a Scanner class to accept user input
        Scanner myScanner = new Scanner(System.in);
	    
		System.out.println("This program will generate a number of random integers between 0 and 50 ");
	    System.out.println("to be used to calculate the Standard Deviation for both the full set and a sample set of those integers.");
		System.out.println("Please enter an integer between 10 and 100 to choose the number of integers to be generated:");       
	    
		int userCount = myScanner.nextInt();
		
		int myIntegers[] = new int[userCount]; //creates an array of integers
		
		Random myRandom = new Random();	

		for(int i = 0; i < myIntegers.length; i++)
		{
			myIntegers[i] = myRandom.nextInt(50); //generates a random integer between 0 and 50 and stores it in an array.
		    System.out.println("This loop will print out each random integer stored in myInteger array: " + i + " value is: " + myIntegers[i]);
		}
		
		//First Class for the Standard Deviation of the population.
		PopulationSD myPopSD = new PopulationSD();
	
		System.out.println();
		System.out.println("This is the average of the " + myIntegers.length + " random integers between 0 and 50: " + myPopSD.calculateAverage(myIntegers));
		System.out.println("This is the standard deviation for the population of those integers: " + myPopSD.calculateSD(myIntegers));
		
		//Second Class for the Standard Deviation of a sample set of the full population.
		SampleSD mySampleSD = new SampleSD();
	
	    System.out.println();
		System.out.println("This is the average of a sample of the random integers: " + mySampleSD.calculateAverage(myIntegers));
		System.out.println("This is the standard deviation for a sample of the random integers: " + mySampleSD.calculateSD(myIntegers));
		System.out.println("(the sample was generated by chosing " + mySampleSD.sampleCounter + " even numbers from the random set.)");
		
  }
}
